/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /** Root */
    get: operations["root__get"];
  };
  "/geo": {
    /** Geo */
    get: operations["geo_geo_get"];
  };
  "/agencies": {
    /** Agencies */
    get: operations["agencies_agencies_get"];
  };
  "/reviews": {
    /** Reviews */
    get: operations["reviews_reviews_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Agency */
    Agency: {
      /** Id */
      id: number;
      /** Geo Id */
      geo_id: number;
      /** Agency Id */
      agency_id: number;
      /** 등록번호 */
      "등록번호": string;
      /** 상호 */
      "상호": string;
      /** 소재지 */
      "소재지": string;
      /** 대표자 */
      "대표자": string;
      /** 등록일자 */
      "등록일자": string;
      /** 상태 */
      "상태": string;
      /** 행정처분시작일자 */
      "행정처분시작일자": string | null;
      /** 행정처분종료일자 */
      "행정처분종료일자": string | null;
      review: components["schemas"]["AgencyReview"];
    };
    /** AgencyReview */
    AgencyReview: {
      /** Items */
      items: components["schemas"]["Review"][];
      /** Average */
      average: number;
    };
    /** GeoItem */
    GeoItem: {
      /** Id */
      id: number;
      /** Sido */
      sido: string;
      /** Sigungu */
      sigungu: string;
      /** Dong */
      dong: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Review */
    Review: {
      /** Id */
      id: number;
      /** Agency Id */
      agency_id: number;
      /** Username */
      username: string;
      /** Point */
      point: number;
      /** Date */
      date: string;
      /** Text */
      text: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Geo */
  geo_geo_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GeoItem"][];
        };
      };
    };
  };
  /** Agencies */
  agencies_agencies_get: {
    parameters: {
      query: {
        geo_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agency"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reviews */
  reviews_reviews_get: {
    parameters: {
      query: {
        agency_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Review"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
